package com.maximeroussy.invitrode;

import com.maximeroussy.invitrode.pick.Pick;

import static java.util.Arrays.asList;

class WordGenerator {

    //-----------------------------------------------------------------------------------------
    //Bigram source and general concept based on https://github.com/scrollback/scrollback & described in https://www.hackerearth.com/notes/random-pronouncable-text-generator/
    //-----------------------------------------------------------------------------------------
    private static final String[] START_BI_GRAM = new String[]{
            "TH",
            "OF",
            "AN",
            "IN",
            "TO",
            "CO",
            "BE",
            "HE",
            "RE",
            "HA",
            "WA",
            "FO",
            "WH",
            "MA",
            "WI",
            "ON",
            "HI",
            "PR",
            "ST",
            "NO",
            "IS",
            "IT",
            "SE",
            "WE",
            "AS",
            "CA",
            "DE",
            "SO",
            "MO",
            "SH",
            "DI",
            "AL",
            "AR",
            "LI",
            "WO",
            "FR",
            "PA",
            "ME",
            "AT",
            "SU",
            "BU",
            "SA",
            "FI",
            "NE",
            "CH",
            "PO",
            "HO",
            "DO",
            "OR",
            "UN",
            "LO",
            "EX",
            "BY",
            "FA",
            "LA",
            "LE",
            "PE",
            "MI",
            "SI",
            "YO",
            "TR",
            "BA",
            "GO",
            "BO",
            "GR",
            "TE",
            "EN",
            "OU",
            "RA",
            "AC",
            "FE",
            "PL",
            "CL",
            "SP",
            "BR",
            "EV",
            "TA",
            "DA",
            "AB",
            "TI",
            "RO",
            "MU",
            "EA",
            "NA",
            "SC",
            "AD",
            "GE",
            "YE",
            "AF",
            "AG",
            "UP",
            "AP",
            "DR",
            "US",
            "PU",
            "CE",
            "IF",
            "RI",
            "VI",
            "IM",
            "AM",
            "KN",
            "OP",
            "CR",
            "OT",
            "JU",
            "QU",
            "TW",
            "GA",
            "VA",
            "VE",
            "PI",
            "GI",
            "BI",
            "FL",
            "BL",
            "EL",
            "JO",
            "FU",
            "HU",
            "CU",
            "RU",
            "OV",
            "MY",
            "OB",
            "KE",
            "EF",
            "PH",
            "CI",
            "KI",
            "NI",
            "SL",
            "EM",
            "SM",
            "VO",
            "MR",
            "WR",
            "ES",
            "DU",
            "TU",
            "AU",
            "NU",
            "GU",
            "OW",
            "SY",
            "JA",
            "OC",
            "EC",
            "ED",
            "ID",
            "JE",
            "AI",
            "EI",
            "SK",
            "OL",
            "GL",
            "EQ",
            "LU",
            "AV",
            "SW",
            "AW",
            "EY",
            "TY"
    };

    public static final String[] BIGRAM_INDEXES = new String[]{
            "TH",
            "AN",
            "IN",
            "IO",
            "EN",
            "TI",
            "FO",
            "HE",
            "HA",
            "HI",
            "TE",
            "AT",
            "ER",
            "AL",
            "WA",
            "VE",
            "CO",
            "RE",
            "IT",
            "WI",
            "ME",
            "NC",
            "ON",
            "PR",
            "AR",
            "ES",
            "EV",
            "ST",
            "EA",
            "IV",
            "EC",
            "NO",
            "OU",
            "PE",
            "IL",
            "IS",
            "MA",
            "AV",
            "OM",
            "IC",
            "GH",
            "DE",
            "AI",
            "CT",
            "IG",
            "ID",
            "OR",
            "OV",
            "UL",
            "YO",
            "BU",
            "RA",
            "FR",
            "RO",
            "WH",
            "OT",
            "BL",
            "NT",
            "UN",
            "TR",
            "HO",
            "AC",
            "TU",
            "WE",
            "CA",
            "SH",
            "UR",
            "IE",
            "PA",
            "TO",
            "EE",
            "LI",
            "RI",
            "UG",
            "AM",
            "ND",
            "US",
            "LL",
            "AS",
            "TA",
            "LE",
            "MO",
            "WO",
            "MI",
            "AB",
            "EL",
            "IA",
            "NA",
            "SS",
            "AG",
            "TT",
            "NE",
            "PL",
            "LA",
            "OS",
            "CE",
            "DI",
            "BE",
            "AP",
            "SI",
            "NI",
            "OW",
            "SO",
            "AK",
            "CH",
            "EM",
            "IM",
            "SE",
            "NS",
            "PO",
            "EI",
            "EX",
            "KI",
            "UC",
            "AD",
            "GR",
            "IR",
            "NG",
            "OP",
            "SP",
            "OL",
            "DA",
            "NL",
            "TL",
            "LO",
            "BO",
            "RS",
            "FE",
            "FI",
            "SU",
            "GE",
            "MP",
            "UA",
            "OO",
            "RT",
            "SA",
            "CR",
            "FF",
            "IK",
            "MB",
            "KE",
            "FA",
            "CI",
            "EQ",
            "AF",
            "ET",
            "AY",
            "MU",
            "UE",
            "HR",
            "TW",
            "GI",
            "OI",
            "VI",
            "CU",
            "FU",
            "ED",
            "QU",
            "UT",
            "RC",
            "OF",
            "CL",
            "FT",
            "IZ",
            "PP",
            "RG",
            "DU",
            "RM",
            "YE",
            "RL",
            "DO",
            "AU",
            "EP",
            "BA",
            "JU",
            "RD",
            "RU",
            "OG",
            "BR",
            "EF",
            "KN",
            "LS",
            "GA",
            "PI",
            "YI",
            "BI",
            "IB",
            "UB",
            "VA",
            "OC",
            "IF",
            "RN",
            "RR",
            "SC",
            "TC",
            "CK",
            "DG",
            "DR",
            "MM",
            "NN",
            "OD",
            "RV",
            "UD",
            "XP",
            "JE",
            "UM",
            "EG",
            "DL",
            "PH",
            "SL",
            "GO",
            "CC",
            "LU",
            "OA",
            "PU",
            "UI",
            "YS",
            "ZA",
            "HU",
            "MR",
            "OE",
            "SY",
            "EO",
            "TY",
            "UP",
            "FL",
            "LM",
            "NF",
            "RP",
            "OH",
            "NU",
            "XA",
            "OB",
            "VO",
            "DM",
            "GN",
            "LD",
            "PT",
            "SK",
            "WR",
            "JO",
            "LT",
            "YT",
            "UF",
            "BJ",
            "DD",
            "EY",
            "GG",
            "GL",
            "GU",
            "HT",
            "LV",
            "MS",
            "NM",
            "NV",
            "OK",
            "PM",
            "RK",
            "SW",
            "TM",
            "XC",
            "ZE",
            "AW",
            "SM"
    };

    public static final String[][][] PRONOUNCEABLE_NEXT_CHARACTERS = new String[][][]{
        /* TH */ {{"E", "A", "I", "O", "R"}, {"E", "O"}},
        /* AN */ {{"D", "T", "Y", "C", "S", "G", "N", "I", "O", "E", "A", "K"}, {"D", "T", "Y", "S", "G", "O", "E", "A", "K"}},
        /* IN */ {{"G", "T", "E", "D", "S", "C", "A", "I", "K", "V", "U", "N", "F"}, {"G", "T", "E", "D", "S", "A", "K"}},
        /* IO */ {{"N", "U", "R"}, {"N", "U", "R"}},
        /* EN */ {{"T", "C", "D", "S", "E", "I", "G", "O", "N", "A"}, {"T", "D", "S", "E", "G", "O", "A"}},
        /* TI */ {{"O", "N", "C", "V", "M", "L", "E", "T", "S", "A", "R", "F"}, {"N", "C", "M", "L", "E", "T", "S", "A", "R", "F"}},
        /* FO */ {{"R", "U", "O", "L"}, {"R", "U", "O", "L"}},
        /* HE */ {{"R", "N", "Y", "S", "M", "I", "A", "L", "D", "T"}, {"R", "N", "Y", "S", "M", "A", "L", "D", "T"}},
        /* HA */ {{"T", "D", "V", "N", "S", "R", "P", "L"}, {"T", "D", "N", "S", "R", "L"}},
        /* HI */ {{"S", "N", "C", "M", "L", "P", "G", "T", "R", "E"}, {"S", "N", "C", "M", "L", "P", "G", "T", "R", "E"}},
        /* TE */ {{"R", "D", "N", "S", "M", "L", "E", "C", "A"}, {"R", "D", "N", "S", "M", "L", "E", "A"}},
        /* AT */ {{"I", "E", "T", "H", "U", "O", "C"}, {"E", "H", "O"}},
        /* ER */ {{"E", "S", "I", "A", "N", "Y", "T", "V", "M", "R", "O", "L", "G", "F", "C"}, {"E", "S", "A", "N", "Y", "T", "M"}},
        /* AL */ {{"L", "S", "I", "T", "E", "U", "O", "M", "K", "F", "A"}, {"L", "S", "T", "E", "F"}},
        /* WA */ {{"S", "Y", "R", "T", "N", "L"}, {"S", "Y", "R", "T", "N", "L"}},
        /* VE */ {{"R", "N", "L", "S", "D"}, {"R", "N", "L", "S", "D"}},
        /* CO */ {{"N", "M", "U", "R", "L", "V", "S", "O"}, {"N", "M", "U", "R", "L", "O"}},
        /* RE */ {{"S", "A", "D", "N", "E", "C", "L", "T", "P", "M", "V", "G", "F", "Q"}, {"S", "A", "D", "N", "E", "L", "T", "P", "M"}},
        /* IT */ {{"H", "I", "Y", "E", "S", "T", "A", "U"}, {"H", "Y", "E", "S", "A"}},
        /* WI */ {{"T", "L", "N", "S"}, {"T", "L", "N", "S"}},
        /* ME */ {{"N", "R", "D", "T", "S", "M", "A"}, {"N", "R", "D", "T", "S", "M", "A"}},
        /* NC */ {{"E", "I", "H", "T", "R", "O", "L"}, {"E", "H", "T"}},
        /* ON */ {{"S", "E", "T", "G", "A", "D", "L", "C", "V", "O", "I", "F"}, {"S", "E", "T", "G", "A", "D", "O"}},
        /* PR */ {{"O", "E", "I", "A"}, {"E", "A"}},
        /* AR */ {{"E", "T", "D", "Y", "S", "I", "R", "L", "M", "K", "G", "A", "O", "N", "C"}, {"E", "T", "D", "Y", "S", "M", "K", "A", "N"}},
        /* ES */ {{"S", "T", "E", "I", "P", "U", "C"}, {"S", "T", "E"}},
        /* EV */ {{"E", "I"}, {"E"}},
        /* ST */ {{"A", "R", "I", "E", "O", "U", "S"}, {"A", "E", "O", "S"}},
        /* EA */ {{"R", "S", "T", "D", "L", "C", "N", "V", "M", "K"}, {"R", "S", "T", "D", "L", "N", "M"}},
        /* IV */ {{"E", "I", "A"}, {"E"}},
        /* EC */ {{"T", "O", "I", "E", "A", "U", "R", "H"}, {"T", "E", "H"}},
        /* NO */ {{"T", "W", "R", "U", "N", "M"}, {"T", "W", "R", "U", "N", "M"}},
        /* OU */ {{"T", "L", "R", "N", "S", "G", "P", "B"}, {"T", "L", "R", "N", "S", "P"}},
        /* PE */ {{"R", "N", "C", "A", "D", "T", "O"}, {"R", "N", "A", "D", "T"}},
        /* IL */ {{"L", "E", "I", "Y", "D", "A"}, {"L", "E", "Y", "D"}},
        /* IS */ {{"T", "H", "S", "I", "E", "C", "M"}, {"T", "H", "S", "E", "M"}},
        /* MA */ {{"N", "T", "L", "K", "D", "S", "I", "G"}, {"N", "T", "L", "D", "S"}},
        /* AV */ {{"E", "I", "A"}, {"E"}},
        /* OM */ {{"E", "P", "M", "I", "A"}, {"E"}},
        /* IC */ {{"A", "H", "E", "I", "T", "K", "U", "S"}, {"H", "E", "T", "K", "S"}},
        /* GH */ {{"T"}, {"T"}},
        /* DE */ {{"R", "N", "S", "D", "A", "V", "P", "T", "M", "L", "F"}, {"R", "N", "S", "D", "A", "P", "T", "M", "L"}},
        /* AI */ {{"N", "D", "R", "L", "T"}, {"N", "D", "R", "L", "T"}},
        /* CT */ {{"I", "E", "U", "S", "O"}, {"E", "S", "O"}},
        /* IG */ {{"H", "N", "I"}, {"H", "N"}},
        /* ID */ {{"E"}, {"E"}},
        /* OR */ {{"E", "T", "M", "D", "S", "K", "I", "Y", "L", "G", "A", "R", "N", "C"}, {"E", "T", "M", "D", "S", "K", "Y", "A", "N"}},
        /* OV */ {{"E", "I"}, {"E"}},
        /* UL */ {{"D", "T", "A", "L"}, {"D", "T", "L"}},
        /* YO */ {{"U"}, {"U"}},
        /* BU */ {{"T", "S", "R", "I"}, {"T", "S", "R"}},
        /* RA */ {{"T", "N", "L", "C", "I", "M", "D", "S", "R", "P", "G", "B"}, {"T", "N", "L", "M", "D", "S", "R"}},
        /* FR */ {{"O", "E", "A"}, {"E", "A"}},
        /* RO */ {{"M", "U", "V", "P", "N", "W", "S", "O", "L", "D", "C", "B", "A", "T", "G"}, {"M", "U", "P", "N", "W", "O", "L", "D", "T"}},
        /* WH */ {{"I", "E", "O", "A"}, {"E", "O"}},
        /* OT */ {{"H", "E", "T", "I"}, {"H", "E"}},
        /* BL */ {{"E", "I", "Y", "O", "A"}, {"E", "Y"}},
        /* NT */ {{"E", "I", "S", "R", "O", "A", "L", "Y", "U", "H"}, {"E", "S", "O", "A", "Y", "H"}},
        /* UN */ {{"D", "T", "I", "C", "G"}, {"D", "T", "G"}},
        /* TR */ {{"A", "I", "O", "E", "U", "Y"}, {"A", "E", "Y"}},
        /* HO */ {{"U", "W", "S", "R", "L", "O", "M", "T", "P", "N", "D"}, {"U", "W", "R", "L", "O", "M", "T", "P", "N", "D"}},
        /* AC */ {{"T", "E", "K", "H", "C", "R", "I"}, {"T", "E", "K", "H"}},
        /* TU */ {{"R", "D", "A", "T"}, {"R", "T"}},
        /* WE */ {{"R", "L", "E", "V", "S", "N", "A"}, {"R", "L", "E", "S", "N", "A"}},
        /* CA */ {{"L", "N", "T", "R", "U", "S", "M", "P"}, {"L", "N", "T", "R", "S", "M"}},
        /* SH */ {{"E", "O", "I", "A"}, {"E", "O"}},
        /* UR */ {{"E", "N", "T", "S", "I", "A", "Y", "R", "P", "C"}, {"E", "N", "T", "S", "A", "Y"}},
        /* IE */ {{"S", "N", "D", "T", "W", "V", "R", "L", "F"}, {"S", "N", "D", "T", "W", "R", "L"}},
        /* PA */ {{"R", "T", "S", "N", "L", "I", "C"}, {"R", "T", "S", "N", "L"}},
        /* TO */ {{"R", "O", "N", "W", "P", "M", "L"}, {"R", "O", "N", "W", "P", "M", "L"}},
        /* EE */ {{"N", "D", "T", "M", "S", "R", "P", "L", "K"}, {"N", "D", "T", "M", "S", "R", "P", "L", "K"}},
        /* LI */ {{"N", "T", "S", "C", "K", "G", "E", "F", "Z", "V", "O", "M", "A"}, {"N", "T", "S", "C", "G", "E", "F", "M", "A"}},
        /* RI */ {{"N", "E", "C", "T", "S", "G", "A", "V", "O", "P", "M", "L", "D", "B"}, {"N", "E", "C", "T", "S", "G", "A", "P", "M", "L", "D"}},
        /* UG */ {{"H", "G"}, {"H"}},
        /* AM */ {{"E", "P", "I", "O", "A"}, {"E"}},
        /* ND */ {{"E", "I", "S", "A", "U", "O"}, {"E", "S", "O"}},
        /* US */ {{"E", "T", "I", "S", "L", "H"}, {"E", "T", "S", "H"}},
        /* LL */ {{"Y", "E", "O", "I", "S", "A"}, {"Y", "E", "S"}},
        /* AS */ {{"T", "S", "E", "I", "U", "O", "K", "H"}, {"T", "S", "E", "O", "H"}},
        /* TA */ {{"T", "N", "L", "I", "R", "K", "B", "G", "C"}, {"T", "N", "L", "R"}},
        /* LE */ {{"S", "D", "A", "T", "C", "R", "N", "M", "G", "V", "F"}, {"S", "D", "A", "T", "R", "N", "M"}},
        /* MO */ {{"R", "S", "V", "T", "U", "D"}, {"R", "T", "U", "D"}},
        /* WO */ {{"R", "U"}, {"R", "U"}},
        /* MI */ {{"N", "L", "S", "T", "C", "G"}, {"N", "L", "S", "T", "C", "G"}},
        /* AB */ {{"L", "O", "I"}, {}},
        /* EL */ {{"L", "Y", "I", "E", "F", "O", "A", "T", "S", "P", "D"}, {"L", "Y", "E", "F", "T", "S", "D"}},
        /* IA */ {{"L", "N", "T"}, {"L", "N", "T"}},
        /* NA */ {{"L", "T", "R", "N", "M"}, {"L", "T", "R", "N", "M"}},
        /* SS */ {{"I", "E", "U", "O", "A"}, {"E", "O"}},
        /* AG */ {{"E", "A", "O"}, {"E", "O"}},
        /* TT */ {{"E", "L", "I"}, {"E"}},
        /* NE */ {{"D", "S", "W", "R", "E", "Y", "V", "T", "L", "C", "A"}, {"D", "S", "W", "R", "E", "Y", "T", "L", "A"}},
        /* PL */ {{"A", "E", "I", "Y", "O"}, {"E", "Y"}},
        /* LA */ {{"T", "N", "R", "S", "C", "Y", "W", "I", "B"}, {"T", "N", "R", "S", "Y", "W"}},
        /* OS */ {{"T", "E", "S", "I"}, {"T", "E", "S"}},
        /* CE */ {{"S", "N", "R", "D", "P", "L", "I"}, {"S", "N", "R", "D", "P", "L"}},
        /* DI */ {{"S", "N", "T", "D", "F", "E", "C", "A", "V", "R"}, {"S", "N", "T", "D", "F", "E", "C", "A", "R"}},
        /* BE */ {{"R", "E", "C", "T", "L", "F", "S", "I", "G", "D", "A"}, {"R", "E", "T", "L", "S", "D", "A"}},
        /* AP */ {{"P", "E", "A"}, {"E"}},
        /* SI */ {{"O", "N", "D", "T", "S", "G", "C", "B", "V", "M", "A"}, {"N", "D", "T", "S", "G", "C", "M", "A"}},
        /* NI */ {{"N", "T", "S", "C", "Z", "O", "G", "F"}, {"N", "T", "S", "C", "G", "F"}},
        /* OW */ {{"N", "E", "S", "I", "A"}, {"N", "E", "S"}},
        /* SO */ {{"N", "M", "U", "L", "C", "R"}, {"N", "M", "U", "L", "R"}},
        /* AK */ {{"E", "I"}, {"E"}},
        /* CH */ {{"E", "A", "I", "O", "U", "R"}, {"E", "O"}},
        /* EM */ {{"E", "S", "P", "O", "B", "A", "I"}, {"E", "S"}},
        /* IM */ {{"E", "P", "I", "A", "S", "M"}, {"E", "S"}},
        /* SE */ {{"D", "N", "L", "S", "R", "E", "C", "T", "V", "A"}, {"D", "N", "L", "S", "R", "E", "T", "A"}},
        /* NS */ {{"T", "I", "E"}, {"T", "E"}},
        /* PO */ {{"S", "R", "N", "L", "W", "T", "I"}, {"R", "N", "L", "W", "T"}},
        /* EI */ {{"R", "N", "G", "T"}, {"R", "N", "G", "T"}},
        /* EX */ {{"P", "T", "I", "C", "A"}, {"T"}},
        /* KI */ {{"N"}, {"N"}},
        /* UC */ {{"H", "T", "K", "E"}, {"H", "T", "K", "E"}},
        /* AD */ {{"E", "I", "Y", "V", "M", "D"}, {"E", "Y"}},
        /* GR */ {{"E", "A", "O"}, {"E", "A"}},
        /* IR */ {{"E", "S", "T", "L", "I"}, {"E", "S", "T"}},
        /* NG */ {{"E", "S", "L", "T", "R", "I"}, {"E", "S"}},
        /* OP */ {{"E", "P", "L"}, {"E"}},
        /* SP */ {{"E", "O", "I", "A"}, {"E"}},
        /* OL */ {{"D", "L", "I", "O", "E", "U"}, {"D", "L", "E"}},
        /* DA */ {{"Y", "T", "R", "N"}, {"Y", "T", "R", "N"}},
        /* NL */ {{"Y"}, {"Y"}},
        /* TL */ {{"Y", "E"}, {"Y", "E"}},
        /* LO */ {{"W", "N", "O", "S", "C", "V", "U", "T", "R", "P", "G"}, {"W", "N", "O", "U", "T", "R", "P"}},
        /* BO */ {{"U", "T", "R", "O", "D", "A"}, {"U", "T", "R", "O", "D"}},
        /* RS */ {{"T", "E", "O", "I"}, {"T", "E", "O"}},
        /* FE */ {{"R", "E", "W", "L", "C", "A"}, {"R", "E", "W", "L", "A"}},
        /* FI */ {{"R", "N", "C", "E", "L", "G"}, {"R", "N", "C", "E", "L", "G"}},
        /* SU */ {{"R", "C", "P", "B", "M", "L", "A"}, {"R", "P", "M", "L"}},
        /* GE */ {{"N", "T", "S", "R", "D"}, {"N", "T", "S", "R", "D"}},
        /* MP */ {{"L", "O", "A", "T", "R", "E"}, {"T", "E"}},
        /* UA */ {{"L", "T", "R"}, {"L", "T", "R"}},
        /* OO */ {{"K", "D", "L", "T", "R", "N", "M"}, {"K", "D", "L", "T", "R", "N", "M"}},
        /* RT */ {{"I", "H", "A", "E", "Y", "U", "S"}, {"H", "A", "E", "Y", "S"}},
        /* SA */ {{"I", "M", "Y", "N", "L"}, {"M", "Y", "N", "L"}},
        /* CR */ {{"E", "I", "O", "A"}, {"E", "A"}},
        /* FF */ {{"E", "I"}, {"E"}},
        /* IK */ {{"E"}, {"E"}},
        /* MB */ {{"E"}, {"E"}},
        /* KE */ {{"D", "N", "T", "S", "R", "E"}, {"D", "N", "T", "S", "R", "E"}},
        /* FA */ {{"C", "R", "M", "I"}, {"R", "M"}},
        /* CI */ {{"A", "T", "E", "S", "P", "N"}, {"A", "T", "E", "S", "P", "N"}},
        /* EQ */ {{"U"}, {}},
        /* AF */ {{"T", "F"}, {"T", "F"}},
        /* ET */ {{"T", "I", "H", "E", "Y", "W", "S", "A"}, {"H", "E", "Y", "S", "A"}},
        /* AY */ {{"S", "E"}, {"S"}},
        /* MU */ {{"S", "N", "L", "C"}, {"S", "N", "L"}},
        /* UE */ {{"S", "N"}, {"S", "N"}},
        /* HR */ {{"O", "E", "I"}, {"E"}},
        /* TW */ {{"O", "E"}, {"O", "E"}},
        /* GI */ {{"N", "V", "O", "C"}, {"N", "C"}},
        /* OI */ {{"N"}, {"N"}},
        /* VI */ {{"N", "D", "S", "C", "T", "O", "L", "E"}, {"N", "D", "S", "C", "T", "L", "E"}},
        /* CU */ {{"L", "R", "T", "S"}, {"L", "R", "T", "S"}},
        /* FU */ {{"L", "R", "N"}, {"L", "R", "N"}},
        /* ED */ {{"I", "U", "E"}, {"E"}},
        /* QU */ {{"I", "E", "A"}, {"E"}},
        /* UT */ {{"I", "H", "E"}, {"H", "E"}},
        /* RC */ {{"H", "E"}, {"H", "E"}},
        /* OF */ {{"F", "T"}, {"F", "T"}},
        /* CL */ {{"E", "A", "U", "O"}, {"E"}},
        /* FT */ {{"E"}, {"E"}},
        /* IZ */ {{"E", "A"}, {"E"}},
        /* PP */ {{"E", "O", "R", "L"}, {"E"}},
        /* RG */ {{"E", "A"}, {"E"}},
        /* DU */ {{"C", "S", "R", "A"}, {"S", "R"}},
        /* RM */ {{"A", "S", "I", "E"}, {"S", "E"}},
        /* YE */ {{"A", "S", "D"}, {"A", "S", "D"}},
        /* RL */ {{"Y", "D"}, {"Y", "D"}},
        /* DO */ {{"W", "N", "M", "E"}, {"W", "N", "M"}},
        /* AU */ {{"T", "S"}, {"T", "S"}},
        /* EP */ {{"T", "O", "E", "A"}, {"T", "E"}},
        /* BA */ {{"S", "C", "R", "N", "L"}, {"S", "R", "N", "L"}},
        /* JU */ {{"S"}, {"S"}},
        /* RD */ {{"S", "E", "I"}, {"S", "E"}},
        /* RU */ {{"S", "N", "C"}, {"S", "N"}},
        /* OG */ {{"R", "I"}, {}},
        /* BR */ {{"O", "I", "E", "A"}, {"E", "A"}},
        /* EF */ {{"O", "F", "U", "T", "E"}, {"F", "T", "E"}},
        /* KN */ {{"O", "E"}, {"O", "E"}},
        /* LS */ {{"O"}, {"O"}},
        /* GA */ {{"N", "I", "T", "R"}, {"N", "T", "R"}},
        /* PI */ {{"N", "T", "R", "E", "C"}, {"N", "T", "R", "E", "C"}},
        /* YI */ {{"N"}, {"N"}},
        /* BI */ {{"L", "T", "N"}, {"L", "T", "N"}},
        /* IB */ {{"L", "I", "E"}, {"E"}},
        /* UB */ {{"L"}, {}},
        /* VA */ {{"L", "T", "R", "N"}, {"L", "T", "R", "N"}},
        /* OC */ {{"K", "I", "E", "C", "A"}, {"K", "E"}},
        /* IF */ {{"I", "F", "E", "T"}, {"F", "E", "T"}},
        /* RN */ {{"I", "E", "M", "A"}, {"E", "A"}},
        /* RR */ {{"I", "E", "Y", "O"}, {"E", "Y"}},
        /* SC */ {{"H", "R", "O", "I", "A"}, {"H"}},
        /* TC */ {{"H"}, {"H"}},
        /* CK */ {{"E"}, {"E"}},
        /* DG */ {{"E"}, {"E"}},
        /* DR */ {{"E", "O", "I", "A"}, {"E", "A"}},
        /* MM */ {{"E", "U", "I"}, {"E"}},
        /* NN */ {{"E", "O", "I"}, {"E", "O"}},
        /* OD */ {{"E", "Y", "U"}, {"E", "Y"}},
        /* RV */ {{"E", "I"}, {"E"}},
        /* UD */ {{"E", "I"}, {"E"}},
        /* XP */ {{"E"}, {"E"}},
        /* JE */ {{"C"}, {}},
        /* UM */ {{"B", "E"}, {"E"}},
        /* EG */ {{"A", "R", "I", "E"}, {"E"}},
        /* DL */ {{"Y", "E"}, {"Y", "E"}},
        /* PH */ {{"Y", "O", "I", "E"}, {"Y", "O", "E"}},
        /* SL */ {{"Y", "A"}, {"Y"}},
        /* GO */ {{"V", "T", "O"}, {"T", "O"}},
        /* CC */ {{"U", "O", "E"}, {"E"}},
        /* LU */ {{"T", "S", "M", "E", "D"}, {"T", "S", "M", "E"}},
        /* OA */ {{"T", "R", "D"}, {"T", "R", "D"}},
        /* PU */ {{"T", "R", "L", "B"}, {"T", "R", "L"}},
        /* UI */ {{"T", "R", "L"}, {"T", "R", "L"}},
        /* YS */ {{"T"}, {"T"}},
        /* ZA */ {{"T"}, {"T"}},
        /* HU */ {{"S", "R", "N", "M"}, {"S", "R", "N", "M"}},
        /* MR */ {{"S"}, {"S"}},
        /* OE */ {{"S"}, {"S"}},
        /* SY */ {{"S"}, {"S"}},
        /* EO */ {{"R", "P"}, {"R", "P"}},
        /* TY */ {{"P"}, {}},
        /* UP */ {{"P", "O"}, {}},
        /* FL */ {{"O", "E"}, {"E"}},
        /* LM */ {{"O"}, {}},
        /* NF */ {{"O"}, {}},
        /* RP */ {{"O"}, {}},
        /* OH */ {{"N"}, {}},
        /* NU */ {{"M"}, {"M"}},
        /* XA */ {{"M"}, {"M"}},
        /* OB */ {{"L"}, {}},
        /* VO */ {{"L"}, {"L"}},
        /* DM */ {{"I"}, {}},
        /* GN */ {{"I"}, {}},
        /* LD */ {{"I", "E"}, {"E"}},
        /* PT */ {{"I"}, {}},
        /* SK */ {{"I", "E"}, {"E"}},
        /* WR */ {{"I"}, {}},
        /* JO */ {{"H"}, {}},
        /* LT */ {{"H", "E"}, {"H", "E"}},
        /* YT */ {{"H"}, {"H"}},
        /* UF */ {{"F"}, {"F"}},
        /* BJ */ {{"E"}, {}},
        /* DD */ {{"E"}, {"E"}},
        /* EY */ {{"E"}, {}},
        /* GG */ {{"E"}, {"E"}},
        /* GL */ {{"E", "A"}, {"E"}},
        /* GU */ {{"E"}, {"E"}},
        /* HT */ {{"E"}, {"E"}},
        /* LV */ {{"E"}, {"E"}},
        /* MS */ {{"E"}, {"E"}},
        /* NM */ {{"E"}, {"E"}},
        /* NV */ {{"E"}, {"E"}},
        /* OK */ {{"E"}, {"E"}},
        /* PM */ {{"E"}, {"E"}},
        /* RK */ {{"E"}, {"E"}},
        /* SW */ {{"E"}, {"E"}},
        /* TM */ {{"E"}, {"E"}},
        /* XC */ {{"E"}, {"E"}},
        /* ZE */ {{"D"}, {"D"}},
        /* AW */ {{"A"}, {}},
        /* SM */ {{"A"}, {}
    }};
    private static final int BIGRAM_LENGTH = 2;

    private final Pick pick;

    WordGenerator(Pick pick) {
        this.pick = pick;
    }

    String generateWord(WordLength wordLength) {
        String randomWord = pick.in(START_BI_GRAM);

        // TODO HMP: 08/12/2017 sortir un concept de mot ?

        int flag = 0; // 0 ou 1
        int count = 0;
        String previousWord;
        while (randomWord.length() != wordLength.wordLength) {
            previousWord = randomWord;
            randomWord = addCharacter(wordLength, randomWord, flag);
            if (previousWord.equals(randomWord)) {
                count++;
            } else {
                flag = 0;
            }
            if (count == 5) {
                flag = 1;
                count++;
            } else if (count == 20) {
                randomWord = pick.in(START_BI_GRAM);
                count = 0;
            }
        }
        return randomWord;
    }

    private String addCharacter(WordLength desiredLength, String currentWord, int flag) {
        boolean lastCharacter = false;
        if (oneCharacterLeft(desiredLength, currentWord)) {
            lastCharacter = true;
        }

        // Cas particulier chelou
        // TODO HMP: 08/12/2017 le cas cas unknown bigram devrait être testé autrement si possible
        while (isUnknownBigram(lastBigram(currentWord)) || noPossibleNextCharacter(currentWord, lastCharacter)) {

            if (isBigram(currentWord)) {
                return pick.in(START_BI_GRAM);
            }
            if (flag == 1) {
                currentWord = backtrack(currentWord, BIGRAM_LENGTH);
                flag = 0;
            } else {
                currentWord = backtrack(currentWord, 1);
            }
            lastCharacter = false;
        }

        return currentWord + nextCharacter(lastCharacter, currentWord);
    }

    private static boolean isBigram(String currentWord) {
        return currentWord.length() == BIGRAM_LENGTH;
    }

    private static boolean oneCharacterLeft(WordLength desiredLength, String currentWord) {
        return currentWord.length() == (desiredLength.wordLength - 1);
    }


    private static boolean isUnknownBigram(String bigram) {
        // TODO HMP: 08/12/2017 ici on devrait logger pour permettre de corriger l'erreur
        return bigramIndex(bigram) < 0 ||
                bigramIndex(bigram) > BIGRAM_INDEXES.length;
    }

    private static boolean noPossibleNextCharacter(String currentWord, boolean lastCharacter) {
        return nextPronounceableCharacters(currentWord, lastCharacter).length <= 0;
    }

    // TODO HMP: 08/12/2017 faire un type bigram

    private static String backtrack(String string, int numberChars) {
        return string.substring(0, string.length() - numberChars);
    }

    // #############################################################

    // Next character

    // #############################################################


    private String nextCharacter(boolean lastCharacter, String word) {
        return pick.in(nextPronounceableCharacters(word, lastCharacter));
    }

    private static String[] nextPronounceableCharacters(String currentWord, boolean lastCharacter) {
        return nextPronounceableCharactersLists(currentWord)[lastCharacter ? 1 : 0];
    }

    private static String[][] nextPronounceableCharactersLists(String currentWord) {
        String lastBigram = lastBigram(currentWord);
        int bigramIndex = bigramIndex(lastBigram);
        return PRONOUNCEABLE_NEXT_CHARACTERS[bigramIndex];
    }

    private static String lastBigram(String word) {
        if (isBigram(word)) {
            return word;
        } else {
            return word.substring(word.length() - BIGRAM_LENGTH);
        }
    }

    private static int bigramIndex(String bigram) {
        return asList(BIGRAM_INDEXES).indexOf(bigram);
    }
}
